In [54]:
import pandas as pd
import numpy as np
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn import preprocessing

In [49]:
train=pd.read_csv('train.csv')
test=pd.read_csv('test.csv')
test=test.drop(columns='id')

In [8]:
## Preprocessing
pd.set_option('max_columns',100)

In [9]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   battery_power  2000 non-null   int64
 1   blue           2000 non-null   int64
 2   clock_speed    2000 non-null   float64
 3   dual_sim       2000 non-null   int64
 4   fc             2000 non-null   int64
 5   four_g         2000 non-null   int64
 6   int_memory     2000 non-null   int64
 7   m_dep          2000 non-null   float64
 8   mobile_wt      2000 non-null   int64
 9   n_cores        2000 non-null   int64
 10  pc             2000 non-null   int64
 11  px_height      2000 non-null   int64
 12  px_width       2000 non-null   int64
 13  ram            2000 non-null   int64
 14  sc_h           2000 non-null   int64
 15  sc_w           2000 non-null   int64
 16  talk_time      2000 non-null   int64
 17  three_g        2000 non-null   int64
 18  touch_screen   2000 non-null   int64
 19  wifi           2000 non-null   int64
 20  price_range    2000 non-null   int64
dtypes: float64(2), int64(19)
memory usage: 328.2 KB

In [10]:
train.describe()

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,pc,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
count,2000.000000,2000.0000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000
mean,1238.518500,0.4950,1.522250,0.509500,4.309500,0.521500,32.046500,0.501750,140.249000,4.520500,9.916500,645.108000,1251.515500,2124.213000,12.306500,5.767000,11.011000,0.761500,0.503000,0.507000,1.500000
std,439.418206,0.5001,0.816004,0.500035,4.341444,0.499662,18.145715,0.288416,35.399655,2.287837,6.064315,443.780811,432.199447,1084.732044,4.213245,4.356398,5.463955,0.426273,0.500116,0.500076,1.118314
min,501.000000,0.0000,0.500000,0.000000,0.000000,0.000000,2.000000,0.100000,80.000000,1.000000,0.000000,0.000000,500.000000,256.000000,5.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000
25%,851.750000,0.0000,0.700000,0.000000,1.000000,0.000000,16.000000,0.200000,109.000000,3.000000,5.000000,282.750000,874.750000,1207.500000,9.000000,2.000000,6.000000,1.000000,0.000000,0.000000,0.750000
50%,1226.000000,0.0000,1.500000,1.000000,3.000000,1.000000,32.000000,0.500000,141.000000,4.000000,10.000000,564.000000,1247.000000,2146.500000,12.000000,5.000000,11.000000,1.000000,1.000000,1.000000,1.500000
75%,1615.250000,1.0000,2.200000,1.000000,7.000000,1.000000,48.000000,0.800000,170.000000,7.000000,15.000000,947.250000,1633.000000,3064.500000,16.000000,9.000000,16.000000,1.000000,1.000000,1.000000,2.250000
max,1998.000000,1.0000,3.000000,1.000000,19.000000,1.000000,64.000000,1.000000,200.000000,8.000000,20.000000,1960.000000,1998.000000,3998.000000,19.000000,18.000000,20.000000,1.000000,1.000000,1.000000,3.000000

In [50]:
y=train['price_range']
X=train.drop(columns=['price_range'])

In [114]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=4,stratify=y,shuffle=True)

In [115]:
gnb = GaussianNB()
y_pred = gnb.fit(X_train, y_train).predict(X_test)
print("Number of mislabeled points out of a total %d points : %d"% (X_test.shape[0], (y_test != y_pred).sum()))
print("Accuracy :",((y_test == y_pred).sum()/X_test.shape[0])*100, "%")

Number of mislabeled points out of a total 200 points : 32
Accuracy : 84.0 %

In [48]:
gnb.predict(test)

array([3, 3, 2, 3, 1, 3, 3, 1, 3, 0, 3, 3, 0, 0, 2, 0, 1, 2, 3, 2, 1, 3,
       1, 1, 3, 0, 2, 0, 3, 0, 2, 0, 3, 0, 0, 1, 3, 1, 2, 2, 1, 2, 0, 0,
       0, 0, 1, 2, 1, 2, 2, 0, 2, 1, 3, 0, 3, 1, 1, 3, 3, 3, 1, 1, 1, 1,
       1, 2, 1, 1, 1, 1, 2, 3, 3, 0, 2, 0, 2, 3, 0, 3, 3, 0, 3, 0, 3, 1,
       2, 0, 1, 1, 2, 0, 2, 1, 0, 2, 1, 3, 1, 0, 0, 2, 1, 2, 0, 1, 2, 3,
       3, 3, 1, 3, 3, 3, 3, 1, 3, 0, 0, 3, 2, 1, 1, 0, 3, 2, 2, 1, 0, 1,
       1, 2, 3, 1, 1, 0, 3, 2, 1, 2, 2, 2, 3, 3, 3, 2, 2, 3, 2, 3, 0, 1,
       2, 2, 3, 3, 3, 3, 2, 2, 3, 3, 3, 3, 1, 0, 3, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 2, 2, 0, 0, 0, 1, 2, 2, 2, 1, 0, 0, 0, 0, 0, 3, 1, 0, 2, 1,
       2, 3, 1, 2, 3, 3, 3, 1, 2, 1, 0, 1, 2, 2, 1, 2, 3, 3, 0, 2, 0, 3,
       2, 2, 2, 0, 0, 1, 0, 3, 0, 1, 0, 2, 2, 1, 3, 0, 3, 0, 3, 1, 2, 0,
       0, 2, 1, 2, 2, 3, 1, 1, 3, 0, 0, 2, 3, 3, 1, 3, 1, 0, 3, 2, 1, 2,
       3, 3, 3, 1, 0, 1, 2, 3, 1, 1, 3, 2, 0, 3, 0, 1, 2, 0, 0, 3, 2, 3,
       2, 2, 1, 3, 2, 2, 3, 2, 2, 1, 1, 0, 2, 3, 1, 0, 0, 3, 0, 3, 1, 1,
       1, 0, 2, 3, 1, 3, 1, 2, 1, 2, 0, 0, 0, 1, 3, 1, 0, 0, 0, 3, 1, 1,
       3, 3, 1, 2, 3, 2, 3, 1, 3, 3, 2, 2, 2, 3, 3, 0, 3, 0, 3, 1, 3, 1,
       3, 3, 0, 1, 1, 3, 1, 3, 1, 3, 0, 0, 0, 0, 2, 0, 1, 1, 1, 1, 1, 2,
       2, 0, 1, 0, 0, 3, 2, 1, 3, 1, 2, 2, 2, 1, 3, 1, 1, 2, 2, 1, 2, 0,
       1, 1, 0, 3, 2, 0, 0, 2, 0, 0, 1, 0, 0, 0, 0, 2, 2, 3, 2, 3, 0, 3,
       1, 3, 0, 1, 0, 1, 2, 0, 3, 2, 3, 3, 1, 3, 1, 3, 1, 3, 2, 1, 2, 2,
       2, 1, 0, 0, 0, 1, 2, 1, 0, 3, 3, 1, 2, 3, 0, 0, 3, 1, 1, 0, 2, 2,
       3, 0, 3, 1, 2, 3, 2, 3, 1, 2, 0, 2, 2, 0, 1, 1, 0, 0, 1, 1, 2, 3,
       3, 3, 2, 3, 1, 1, 2, 2, 3, 3, 1, 1, 3, 2, 2, 2, 1, 0, 2, 2, 0, 1,
       0, 3, 1, 0, 3, 2, 2, 0, 3, 0, 2, 2, 0, 3, 0, 3, 3, 0, 2, 1, 3, 3,
       1, 1, 2, 3, 2, 0, 2, 1, 3, 0, 3, 3, 1, 2, 2, 2, 3, 0, 1, 1, 3, 1,
       3, 2, 3, 1, 1, 1, 0, 3, 1, 0, 3, 2, 3, 2, 0, 3, 3, 3, 2, 3, 3, 1,
       1, 1, 2, 3, 3, 1, 0, 1, 1, 1, 2, 2, 1, 0, 2, 2, 3, 2, 0, 3, 1, 3,
       3, 0, 2, 3, 1, 2, 1, 0, 0, 0, 2, 1, 0, 1, 1, 2, 2, 0, 2, 3, 1, 0,
       3, 0, 0, 3, 2, 0, 0, 0, 0, 0, 3, 0, 3, 1, 3, 2, 1, 3, 3, 0, 1, 1,
       3, 2, 2, 1, 0, 3, 0, 1, 1, 2, 0, 1, 1, 1, 1, 2, 1, 3, 1, 3, 2, 1,
       1, 3, 2, 0, 1, 3, 0, 3, 3, 0, 2, 1, 2, 2, 0, 3, 2, 0, 3, 2, 3, 0,
       0, 3, 0, 1, 2, 3, 2, 1, 2, 2, 2, 1, 3, 0, 1, 0, 2, 2, 1, 0, 0, 1,
       0, 0, 3, 0, 1, 1, 0, 1, 1, 0, 3, 0, 3, 2, 3, 0, 0, 1, 2, 2, 1, 0,
       1, 1, 0, 1, 2, 0, 0, 3, 3, 1, 3, 1, 2, 3, 0, 1, 0, 1, 2, 0, 3, 2,
       0, 3, 1, 1, 0, 2, 3, 2, 2, 3, 0, 3, 2, 0, 1, 0, 2, 3, 2, 0, 2, 1,
       3, 1, 0, 2, 2, 0, 3, 1, 2, 1, 1, 1, 3, 1, 2, 2, 2, 0, 0, 1, 1, 0,
       2, 0, 0, 0, 0, 3, 3, 3, 3, 0, 1, 2, 1, 1, 0, 0, 2, 1, 0, 2, 0, 2,
       2, 2, 2, 2, 0, 2, 1, 3, 0, 0, 3, 1, 3, 0, 0, 2, 2, 2, 1, 3, 3, 2,
       0, 0, 2, 3, 0, 3, 0, 0, 0, 2, 2, 0, 2, 0, 3, 2, 1, 2, 3, 3, 0, 1,
       2, 2, 0, 2, 2, 0, 2, 3, 1, 1, 3, 1, 2, 3, 2, 1, 1, 2, 3, 3, 0, 3,
       3, 0, 2, 3, 2, 2, 2, 3, 2, 0, 1, 2, 0, 2, 1, 1, 1, 3, 2, 1, 2, 0,
       0, 1, 3, 0, 0, 2, 1, 3, 1, 0, 0, 3, 2, 2, 2, 0, 3, 3, 2, 1, 3, 1,
       1, 3, 1, 2, 1, 2, 2, 2, 0, 3, 1, 2, 3, 0, 3, 1, 3, 3, 1, 1, 2, 3,
       1, 0, 1, 1, 3, 1, 3, 0, 2, 2, 0, 2, 3, 3, 3, 0, 2, 1, 1, 1, 2, 3,
       3, 0, 2, 2, 2, 1, 3, 0, 1, 2, 0, 1, 0, 0, 3, 2, 2, 0, 0, 0, 0, 3,
       2, 3, 2, 0, 0, 2, 1, 0, 2, 2])

In [101]:
s_y=train['price_range']
s_X=train.drop(columns=['price_range'])
train_col=train.drop(columns=['price_range']).columns

In [102]:
scaler = preprocessing.StandardScaler().fit(s_X)
s_X=scaler.transform(s_X)

scaler = preprocessing.StandardScaler().fit(test)
scaled_test=scaler.transform(test)

In [103]:
s_X=pd.DataFrame(s_X,columns=train_col)

scaled_test=pd.DataFrame(scaled_test,columns=test.columns)

In [104]:
s_X_train, s_X_test, s_y_train, s_y_test = train_test_split(s_X, s_y, test_size=0.1, random_state=0,stratify=s_y)

In [106]:
gnb = GaussianNB()
y_pred = gnb.fit(s_X_train, s_y_train).predict(s_X_test)
print("Number of mislabeled points out of a total %d points : %d"% (X_test.shape[0], (s_y_test != y_pred).sum()))
print("Accuracy :",((s_y_test == y_pred).sum()/X_test.shape[0])*100, "%")

Number of mislabeled points out of a total 200 points : 34
Accuracy : 83.0 %